[package]
name = "doom_like_fps"
version = "0.1.0"
edition = "2024"

[dependencies]
sdl2 = { version = "0.35", features = ["image", "ttf", "mixer"] }
rand = "0.8"

[[bin]]
name = "doom_like_fps"
path = "src/main.rs"
